name: "Build"

on:
  workflow_call:
    secrets:
      DOCKER_REPOSITORY_NAME:
        required: true
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
  build:
    name: Build, scan and push Docker image
    runs-on: ubuntu-18.04
    outputs:
      digest: ${{ steps.docker_push.outputs.digest }}
    steps:
      - name: Chect out the repo
        uses: actions/checkout@v2

      - name: Docker meta - Define Docker image name and tag
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ${{ secrets.DOCKER_REPOSITORY_NAME }},ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,suffix=-${{ github.run_number }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and export Docker image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Scan Docker image for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v1
        continue-on-error: true
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.run_number }}
          severity_threshold: CRITICAL
          annotations: true
          dockerfile: ./Dockerfile

      - name: Push Docker image
        if: ${{ github.ref_name == 'master' || github.ref_name == 'dev' || contains(github.event.head_commit.message, '[push image]')}}
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.docker_meta.outputs.tags }}

  report:
    name: Report
    needs: [build]
    if: ${{ github.ref_name == 'master' || github.ref_name == 'dev' || contains(github.event.head_commit.message, '[push image]')}}
    runs-on: ubuntu-18.04
    steps:
      - name: Report
        run: |
          echo Docker image name: ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.run_number }}
          echo Digest: ${{ needs.build.outputs.digest }}
